services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: keniding
      MINIO_ROOT_PASSWORD: keniding
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:
    driver: local