spring:
  cloud:
    gateway:
      routes:
        - id: service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: service-roles
          uri: http://localhost:8082
          predicates:
            - Path=/api/roles/**