spring:
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: service-users
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthServiceFilter
        - id: service-roles
          uri: http://localhost:8083
          predicates:
            - Path=/api/roles/**
          filters:
            - name: AuthServiceFilter
        - id: service-project
          uri: http://localhost:8084
          predicates:
            - Path=/api/projects/**
          filters:
            - name: AuthServiceFilter
        - id: service-type
          uri: http://localhost:8085
          predicates:
            - Path=/api/types/**
          filters:
            - name: AuthServiceFilter
        - id: service-category
          uri: http://localhost:8086
          predicates:
            - Path=/api/categories/**
          filters:
            - name: AuthServiceFilter
        - id: service-supplier
          uri: http://localhost:8087
          predicates:
            - Path=/api/suppliers/**
          filters:
            - name: AuthServiceFilter
        - id: service-resource
          uri: http://localhost:8088
          predicates:
            - Path=/api/resources/**
          filters:
            - name: AuthServiceFilter
        - id: service-location
          uri: http://localhost:8089
          predicates:
            - Path=/api/locations/**
          filters:
            - name: AuthServiceFilter
        - id: service-post
          uri: http://localhost:8090
          predicates:
            - Path=/api/posts/**
          filters:
            - name: AuthServiceFilter
        - id: service-staff
          uri: http://localhost:8091
          predicates:
            - Path=/api/staff/**
          filters:
            - name: AuthServiceFilter