spring:
  cloud:
    gateway:
      routes:
        - id: service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthServiceFilter
        - id: service-roles
          uri: http://localhost:8082
          predicates:
            - Path=/api/roles/**
          filters:
            - name: AuthServiceFilter
        - id: service-auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
